from django.urls import path
from .views import (
    RecentConversationsView,
    StartConversationView,
    SearchChatsView,
    SearchUsersView,
    TotalUnreadCountView,
    ChatDetailsView,
    PinChatView,
    ArchiveChatView,
    MuteChatView,
    UnmuteChatView,
    DeleteChatView,
    ClearChatView,
    SetDisappearingMessagesView,
    ReportUserView,
    MarkChatReadView,
    MessageListView,
    SharedMediaView,
    ChatSettingsView,
    SendMessageView,
    SendMediaMessageView,
    DownloadAttachmentView,
    MessageStatusUpdateView,
    MediaUploadUrlView,
    MediaBinaryUploadView,
    MediaCompleteView,
    MediaDetailView,
    MediaDownloadView,
    SearchUsersAPIView,
    SearchChatsAPIView,
    SearchMessagesView,
    UnifiedSearchView,
    TypingIndicatorView,
    InitiateCallView,
    AcceptCallView,
    RejectCallView,
    CancelCallView,
    EndCallView,
    CallDetailView,
    CallHistoryView,
    CallSignalView,
    IceServersView,
    NotificationListView,
    NotificationBadgeView,
    MarkNotificationReadView,
    MarkAllNotificationsReadView,
    DeleteNotificationView,
    MessageReactionView,
    MessageStarView,
    StarredMessageListView,
    MessageDraftListView,
    MessageDraftDetailView,
    ScheduledMessageListView,
)

urlpatterns = [
    path("chats/", RecentConversationsView.as_view()),
    path("chats/start/", StartConversationView.as_view()),
    path("chats/search/", SearchChatsView.as_view()),
    path("chats/users/search/", SearchUsersView.as_view()),
    path("chats/unread-count/", TotalUnreadCountView.as_view()),
    path("chats/<uuid:chat_id>/", ChatDetailsView.as_view()),
    path("chats/<uuid:chat_id>/pin/", PinChatView.as_view()),
    path("chats/<uuid:chat_id>/archive/", ArchiveChatView.as_view()),
    path("chats/<uuid:chat_id>/mute/", MuteChatView.as_view()),
    path("chats/<uuid:chat_id>/unmute/", UnmuteChatView.as_view()),
    path("chats/<uuid:chat_id>/delete/", DeleteChatView.as_view()),
    path("chats/<uuid:chat_id>/clear/", ClearChatView.as_view()),
    path("chats/<uuid:chat_id>/disappearing/", SetDisappearingMessagesView.as_view()),
    path("chats/report/", ReportUserView.as_view()),
    path("chats/<uuid:chat_id>/read/", MarkChatReadView.as_view()),
    path("chats/<uuid:chat_id>/typing/", TypingIndicatorView.as_view()),

    # Message Endpoints
    path("chats/<uuid:chat_id>/messages/", MessageListView.as_view()),
    path("chats/<uuid:chat_id>/media/", SharedMediaView.as_view()),
    path("chats/<uuid:chat_id>/settings/", ChatSettingsView.as_view()),
    path("chats/<uuid:chat_id>/messages/send/", SendMessageView.as_view()),
    path("chats/<uuid:chat_id>/messages/media/", SendMediaMessageView.as_view()),
    path(
        "messages/<uuid:message_id>/attachment/",
        DownloadAttachmentView.as_view(),
        name="message-attachment-download",
    ),
    path("messages/<uuid:message_id>/status/", MessageStatusUpdateView.as_view()),
    path("messages/<uuid:message_id>/reaction/", MessageReactionView.as_view()),
    path("messages/<uuid:message_id>/star/", MessageStarView.as_view()),
    path("messages/starred/", StarredMessageListView.as_view()),
    path("messages/scheduled/", ScheduledMessageListView.as_view()),

    # Drafts
    path("drafts/", MessageDraftListView.as_view()),
    path("drafts/<uuid:pk>/", MessageDraftDetailView.as_view()),

    # In-app notifications + badge
    path("notifications/", NotificationListView.as_view()),
    path("notifications/badge/", NotificationBadgeView.as_view()),
    path("notifications/read-all/", MarkAllNotificationsReadView.as_view()),
    path("notifications/<uuid:notification_id>/read/", MarkNotificationReadView.as_view()),
    path("notifications/<uuid:notification_id>/", DeleteNotificationView.as_view()),

    # Search
    path("search/", UnifiedSearchView.as_view()),
    path("search/users/", SearchUsersAPIView.as_view()),
    path("search/chats/", SearchChatsAPIView.as_view()),
    path("search/messages/", SearchMessagesView.as_view()),

    # Module 4 — Media (presigned upload flow)
    path("media/upload-url/", MediaUploadUrlView.as_view()),
    path("media/complete/", MediaCompleteView.as_view()),
    path("media/<uuid:media_id>/", MediaDetailView.as_view()),
    path(
        "media/<uuid:media_id>/upload/",
        MediaBinaryUploadView.as_view(),
        name="media-upload-binary",
    ),
    path(
        "media/<uuid:media_id>/download/",
        MediaDownloadView.as_view(),
        name="media-download",
    ),

    # Voice & Video Calls
    path("calls/ice-servers/", IceServersView.as_view()),
    path("calls/", InitiateCallView.as_view()),
    path("calls/history/", CallHistoryView.as_view()),
    path("calls/<uuid:call_id>/", CallDetailView.as_view()),
    path("calls/<uuid:call_id>/accept/", AcceptCallView.as_view()),
    path("calls/<uuid:call_id>/reject/", RejectCallView.as_view()),
    path("calls/<uuid:call_id>/cancel/", CancelCallView.as_view()),
    path("calls/<uuid:call_id>/end/", EndCallView.as_view()),
    path("calls/<uuid:call_id>/signal/", CallSignalView.as_view()),
]
